# Generated by Django 4.2.4 on 2023-08-25 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar2_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 18, 41, 31, 446349)),
        ),
    ]
